#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t cm"

$L "Welcome to Android `getprop ro.build.version.release` / CYANOSPACEMOD-`getprop ro.space.version`";
$L "================================================";
$L "                  CYANOSPACEMOD                 ";
$L "================================================";
$L "                   SPACECAKER                   ";
$L "================================================";
$L "       PLEASE, IF YOU LIKE MY WORK CONSIDER A   ";
$L "                T H A N K  Y O U                ";
$L "================================================";
$L " ";
